package com.folio.ui.screens.healthcheck

import android.net.Uri
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.folio.data.repository.BillingRepository
import com.folio.data.repository.DocumentRepository
import com.folio.data.repository.HistoryRepository
import com.folio.domain.model.DocumentFile
import com.folio.domain.model.Operation
import com.folio.domain.model.OperationResult
import com.folio.domain.usecase.smart.HealthCheckUseCase
import com.folio.domain.usecase.smart.HealthResult
import com.folio.util.OperationCleanup
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class HealthCheckViewModel @Inject constructor(
    private val healthCheckUseCase: HealthCheckUseCase,
    private val documentRepository: DocumentRepository,
    private val historyRepository: HistoryRepository,
    private val billingRepository: BillingRepository,
    private val operationCleanup: OperationCleanup
) : ViewModel() {

    private val _selectedFile = MutableStateFlow<DocumentFile?>(null)
    val selectedFile: StateFlow<DocumentFile?> = _selectedFile.asStateFlow()

    private val _uiState = MutableStateFlow<HealthCheckUiState>(HealthCheckUiState.Idle)
    val uiState: StateFlow<HealthCheckUiState> = _uiState.asStateFlow()

    val adsRemoved: StateFlow<Boolean> = billingRepository.adsRemoved

    fun selectFile(uri: Uri) {
        _selectedFile.value = documentRepository.getDocumentFile(uri)
        _uiState.value = HealthCheckUiState.Idle
    }

    fun clearAll() {
        _selectedFile.value = null
        _uiState.value = HealthCheckUiState.Idle
    }

    fun runHealthCheck() {
        val file = _selectedFile.value ?: return

        viewModelScope.launch {
            _uiState.value = HealthCheckUiState.Scanning
            when (val result = healthCheckUseCase.execute(file.uri)) {
                is OperationResult.Success -> {
                    _uiState.value = HealthCheckUiState.Result(result.data)
                    historyRepository.logOperation(
                        Operation(toolName = "Health Check", inputFile = file.name, inputSize = file.size, outputFile = file.name, outputSize = file.size, outputPath = "")
                    )
                    operationCleanup.cleanup()
                }
                is OperationResult.Error -> _uiState.value = HealthCheckUiState.Error(result.message)
                is OperationResult.Loading -> {}
            }
        }
    }

    fun generateReportText(): String {
        val state = _uiState.value
        if (state !is HealthCheckUiState.Result) return ""

        val r = state.healthResult
        return buildString {
            appendLine("=== FOLIO PDF HEALTH REPORT ===")
            appendLine()
            appendLine("File: ${r.fileName}")
            appendLine("Size: ${formatBytes(r.fileSize)}")
            appendLine("Pages: ${r.pageCount}")
            appendLine("PDF Version: ${r.pdfVersion}")
            appendLine("Encrypted: ${if (r.isEncrypted) "Yes" else "No"}")
            appendLine("Content: ${r.contentType}")
            appendLine("Has Text: ${if (r.hasText) "Yes" else "No"}")
            appendLine("Has Images: ${if (r.hasImages) "Yes" else "No"}")
            appendLine("Fonts: ${r.embeddedFonts.joinToString(", ").ifEmpty { "None found" }}")
            appendLine()
            if (r.issues.isNotEmpty()) {
                appendLine("--- Issues ---")
                r.issues.forEach { appendLine("[${it.severity}] ${it.message}") }
            }
            if (r.warnings.isNotEmpty()) {
                appendLine("--- Warnings ---")
                r.warnings.forEach { appendLine("⚠ $it") }
            }
            if (r.issues.isEmpty() && r.warnings.isEmpty()) {
                appendLine("✅ No issues found — this PDF is healthy!")
            }
            appendLine()
            appendLine("Report generated by Folio PDF Toolkit")
        }
    }

    private fun formatBytes(bytes: Long): String {
        return when {
            bytes >= 1_073_741_824 -> "%.1f GB".format(bytes / 1_073_741_824.0)
            bytes >= 1_048_576 -> "%.1f MB".format(bytes / 1_048_576.0)
            bytes >= 1024 -> "%.1f KB".format(bytes / 1024.0)
            else -> "$bytes B"
        }
    }
}

sealed class HealthCheckUiState {
    data object Idle : HealthCheckUiState()
    data object Scanning : HealthCheckUiState()
    data class Result(val healthResult: HealthResult) : HealthCheckUiState()
    data class Error(val message: String) : HealthCheckUiState()
}
